import Header from '@/components/Header'
import Footer from '@/components/Footer'

import styles from './layout.module.css'

import { Inter } from 'next/font/google'
import 'normalize.css/normalize.css'
import '@/styles/globals.css'

const inter = Inter({ subsets: ['latin'] })

// Define metadata outside the component
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className + ' ' + styles.body}>
        <Header />
        <main className={styles.main}>
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
